### PR TITLE
fix: unofficial support of node v8

### PR DESCRIPTION
**Pull request by Rauno56**
With some additional changes(installing `jest@25`, and running the working version of the script instead of `npx update-ts-references`), I was also able to run tests, and they pass.
I can add those to this PR + changes to the CI, etc. If you are open to those.

### CODE REVIEW

**Comment by juanpicado** [comment]
Hi @Rauno56, just wondering which env force you to use Node.js 8. It is officially out of support and not recommended to use. Looking forward to know more about it.

**Comment by Rauno56** [comment]
I'm working on [OpenTelemetry](https://github.com/open-telemetry/opentelemetry-js) and we support Node v8 for now. We were thinking of using [update-ts-references](https://github.com/open-telemetry/opentelemetry-js/pull/2448) while restructuring the repository and noticed CI failing on node v8.

**Comment by juanpicado** [comment]
Maybe we should enable Node 8 on the workflow CI

**Comment by juanpicado** [comment]
Futhermore, at package.json level is forbidden, also this should be updated https://github.com/eBayClassifiedsGroup/update-ts-references/blob/master/package.json#L39

**Comment by juanpicado** [comment]
> With some additional changes(installing jest@25, and running the working version of the script instead of npx update-ts-references), I was also able to run tests, and they pass.

Ahh, nevermind, Jest does not support Node 8, well, I guess should not be a problem, but then we cannot change the `package.json`, I guess you could install it ignoring the `engines`.

**Review by juanpicado — APPROVED** [review]
LGTM 👍🏼 , hopefully this helps you.

Answering your question, I think we cannot just downgrade our dependencies, Node10 still the official minimum supported version. 

Thanks for the PR.

**Comment by Rauno56** [comment]
I appreciate your quick replies!

> Answering your question, I think we cannot just downgrade our dependencies, Node10 still the official minimum supported version.

What I was saying was downgrading jest to 25 was sufficient to get the tests working.
That leaves enabling node v8 in CI and it could be officially supported.

Are you saying there is another reason why you definitely want to avoid supporting node 8 officially(compliance or whatnot) or are you against downgrading jest from 26 to 25?

**Comment by juanpicado** [comment]
> What I was saying was downgrading jest to 25 was sufficient to get the tests working.
> That leaves enabling node v8 in CI and it could be officially supported.

I'd vote to help the ecosystem to move forward away from Node8, even Node 10 if is possible. But I understand it is not possible in all cases as you have explained, that's totally fine.

I think downgrade has a lot of disadvantages, lack of support from maintainers, security implications, block project to use other newer dependencies (Eg: Yarn 2 only works Node 12+) , that's the reason why I'd like not to downgrade, thus impossible to enable Node 8 on CI.

But your PR is so small and is not breaking newer Node.js versions, so I think we can live with it, but IMHO I won't like to advertise we support Node 8 😊 even if it works fine for you. I hope you understand my point of view.

**Comment by Rauno56** [comment]
OK. So the conclusion is:
1. This PR can be merged (I'll leave that to you);
2. We're not going to advertise the support for Node v8 in this package(totally fair imho);
3. I'll leave the code for testing node@v8 local to my env.

That solves it for me! I will let you take it from here then. Was a pleasure, thanks!

**Review by MKruschke — APPROVED** [review]

**Comment by MKruschke** [comment]
Hi @Rauno56 ,
I just released the package with applied changes under the version 2.4.1, please be aware that this is an unofficial support of the v8, which had by the way end of life in 2020.

I honestly don't like it, but in favor to unblock you I made an one-time exception here. Please be aware, that this might break in any of the next versions because we will not keeping an eye on it. If you a still need to stick to v8 I recommend to pin the version in your project.

Wish you a nice week and thanks for using the tool and also for your contribution.

Best Mirko

**Pull request merged**
